version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    cooldown:
      default-days: 5
      exclude:
        - 'ffflorian/*'
  - package-ecosystem: 'npm'
    directory: '/coolify-deploy'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 26'
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
  - package-ecosystem: 'npm'
    directory: '/force-release'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 26'
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
  - package-ecosystem: 'npm'
    directory: '/hugo-theme-update'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 26'
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
  - package-ecosystem: 'npm'
    directory: '/yarn-update'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 26'
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
