name: Force Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  force-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ./force-release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
