name: Mirror to Codeberg and GitLab

permissions: {}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror to Codeberg and GitLab
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - uses: ./git-mirror
        with:
          GITLAB_REMOTE: 'git@gitlab.com:${{ github.repository }}.git'
          GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
          GITLAB_PUSH_ALL_REFS: 'false'
          CODEBERG_REMOTE: 'git@codeberg.org:${{ github.repository }}.git'
          CODEBERG_SECRET: ${{ secrets.CODEBERG_SECRET }}
          CODEBERG_PUSH_ALL_REFS: 'false'
