---
name: Lint and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}
jobs:
  lint_publish:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24

      - name: Run prettier
        run: |
          yarn init -y
          yarn add -D -E @ffflorian/prettier-config@0.7.0 prettier@3.8.1
          npx --no prettier -- --list-different .

      - name: Publish all actions
        if: github.event_name != 'pull_request'
        uses: ./github-action-release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          git_author: Florian Imdahl
          git_email: git@ffflorian.de
