name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 26

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check formatting with Prettier
        run: yarn lint

      - name: Type-check
        run: yarn workspaces foreach --all --parallel --exclude actions run type-check

      - name: Run tests
        run: yarn workspaces foreach --all --parallel --exclude actions run test

  build_publish:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 26

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build TypeScript actions
        run: yarn workspaces foreach --all --parallel --exclude actions run build

      - name: Publish all actions
        if: github.event_name != 'pull_request'
        uses: ./github-action-release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          git_author: Florian Imdahl
          git_email: git@ffflorian.de
          publish_files: |
            CHANGELOG.md
            coolify-deploy/dist/index.js
            force-release/dist/index.js
            hugo-theme-update/dist/index.js
            yarn-update/dist/index.js
