name: Check scripts with Shellcheck

on: [push, pull_request]

jobs:
  check_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Run Shellcheck
        run: shellcheck **/*.sh
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
