name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build_test_publish:
    name: Build, test, and publish
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 26
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint, type-check, test, and build
        run: |
          yarn lint
          yarn type-check
          yarn test
          yarn build

      - name: Publish all actions
        if: github.event_name != 'pull_request'
        uses: ./github-action-release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          git_author: Florian Imdahl
          git_email: git@ffflorian.de
          publish_files: |
            CHANGELOG.md
            coolify-deploy/dist/index.js
            force-release/dist/index.js
            hugo-theme-update/dist/index.js
            yarn-update/dist/index.js
